repos:
  - repo: local
    hooks:

      - id: ruff-format
        name: ruff-format
        stages: [commit]
        language: system
        entry: uv run ruff format
        types: [python]

      - id: ruff-check
        name: ruff-check
        stages: [commit]
        language: system
        entry: uv run ruff check --fix
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: uv run mypy
        types: [python]
        pass_filenames: false
